name: Update NextDNS Rewrites

on:
  schedule:
    - cron: '0 0 * * *' # Запускается автоматически раз в сутки
  workflow_dispatch: # Позволяет запускать кнопкой вручную в любое время

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
        env:
          NEXTDNS_API_KEY: ${{ secrets.NEXTDNS_API_KEY }}
          NEXTDNS_PROFILE_ID: ${{ secrets.NEXTDNS_PROFILE_ID }}
        run: python script.py
